import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./ui/nav-bar";
import { auth0 } from "./lib/auth0";
import { FaInstagram } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth0.getSession();

  if (!session) {
    return (
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex items-center justify-center min-h-screen bg-gray-100`}
        >
          <div className="bg-white p-8 rounded-lg shadow-md w-96 text-center">
            <FaInstagram className="text-pink-500 text-5xl mx-auto mb-4" />
            <h2 className="text-2xl font-semibold text-gray-800 mb-4">Welcome to Instagram</h2>
            <p className="text-gray-500 mb-6">Log in to continue</p>

            <a
              href="/auth/login"
              className="w-full py-2 px-4 bg-gradient-to-r from-pink-500 to-orange-500 text-white rounded-full shadow-md text-lg font-semibold hover:scale-105 transition transform duration-200 ease-in-out"
            >
              Login
            </a>
          </div>
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        
        <NavBar />
        {children}
      </body>
    </html>
  );
}
